const reduce=matchMedia('(prefers-reduced-motion: reduce)').matches,clamp=v=>Math.max(0,Math.min(1,v));const journey=document.querySelector('.journey'),photos=[...document.querySelectorAll('.journey-photo')],hero=document.querySelector('.hero-image'),pause=document.querySelector('.pause-image');let busy=false;function update(){const y=scrollY,max=document.documentElement.scrollHeight-innerHeight;document.querySelector('.progress').style.transform=`scaleX(${max?y/max:0})`;if(!reduce){hero.style.transform=`scale(${1.12+clamp(y/innerHeight)*.17}) translateY(${clamp(y/innerHeight)*6}%)`;const r=journey.getBoundingClientRect(),phase=clamp(-r.top/Math.max(1,r.height-innerHeight))*3;photos.forEach((el,i)=>{const inProgress=clamp((phase-i)*1.45);if(i===0){el.style.clipPath='inset(0)';el.style.transform=`scale(${1.16-clamp(phase)*.16})`}else{el.style.clipPath=`inset(${(1-inProgress)*50}% ${(1-inProgress)*50}% round ${(1-inProgress)*220}px)`;el.style.transform=`scale(${1.22-inProgress*.22}) rotate(${(1-inProgress)*(i===1?-10:10)}deg)`}const title=el.querySelector('.photo-label');title.style.opacity=String(clamp(1-Math.abs(phase-(i+.4))*1.2));title.style.transform=`translateY(${(i+.4-phase)*40}px)`});document.querySelector('.journey-number').textContent=`${String(Math.min(3,Math.floor(phase)+1)).padStart(2,'0')} / 03`;document.querySelector('.journey-track i').style.transform=`scaleX(${phase/3})`;const p=pause.parentElement.getBoundingClientRect();if(p.top<innerHeight&&p.bottom>0)pause.style.transform=`scale(${1.2-clamp((innerHeight-p.top)/(p.height+innerHeight))*.2}) translateY(${clamp((innerHeight-p.top)/(p.height+innerHeight))*5}%)`}busy=false}addEventListener('scroll',()=>{if(!busy){busy=true;requestAnimationFrame(update)}},{passive:true});addEventListener('resize',update);update();const obs=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('on');obs.unobserve(e.target)}}),{threshold:.1});document.querySelectorAll('.philosophy h2,.philosophy p,.pause h2,.end h2,.end-main>a').forEach(el=>{el.classList.add('reveal');if(reduce)el.classList.add('on');else obs.observe(el)});

const menuToggle=document.querySelector('.menu-toggle'),mobileNav=document.querySelector('#mobile-nav');
function closeMenu(){mobileNav.hidden=true;menuToggle.setAttribute('aria-expanded','false');menuToggle.setAttribute('aria-label','Abrir menú')}
menuToggle.addEventListener('click',()=>{const opening=mobileNav.hidden;mobileNav.hidden=!opening;menuToggle.setAttribute('aria-expanded',String(opening));menuToggle.setAttribute('aria-label',opening?'Cerrar menú':'Abrir menú')});
mobileNav.querySelectorAll('a').forEach(link=>link.addEventListener('click',closeMenu));
addEventListener('keydown',event=>{if(event.key==='Escape'&&!mobileNav.hidden){closeMenu();menuToggle.focus()}});
addEventListener('resize',()=>{if(innerWidth>700)closeMenu()});

document.querySelector('.hero-image')?.classList.add('cover-visual');

;(()=>{const reduced=matchMedia('(prefers-reduced-motion: reduce)');const chapters=[...document.querySelectorAll('.motion-story')];const headings=[...document.querySelectorAll('main section:not(.hero):not(.motion-story) h2')];headings.forEach(el=>el.classList.add('scroll-heading'));let frame=0;const bounded=v=>Math.max(0,Math.min(1,v));function draw(){frame=0;if(reduced.matches)return;chapters.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const p=bounded(-r.top/Math.max(1,r.height-innerHeight));el.style.setProperty('--chapter-progress',p);el.style.setProperty('--word-x',`${55-p*145}%`);el.style.setProperty('--turn',`${p*150-35}deg`);el.style.setProperty('--shape-scale',.4+p*1.05);const title=el.querySelector('h2');title.style.translate=`0 ${(p-.5)*-65}px`;el.querySelector('.motion-caption').textContent=String(Math.min(3,Math.floor(p*3)+1)).padStart(2,'0')+' / 03'});headings.forEach(el=>{const r=el.getBoundingClientRect();if(r.bottom<0||r.top>innerHeight)return;const p=bounded((innerHeight-r.top)/(innerHeight*.75));el.style.setProperty('--heading-y',`${(1-p)*65}px`);el.style.setProperty('--heading-opacity',.3+p*.7)})}function schedule(){if(!frame)frame=requestAnimationFrame(draw)}addEventListener('scroll',schedule,{passive:true});addEventListener('resize',schedule);reduced.addEventListener('change',()=>{if(reduced.matches){headings.forEach(el=>{el.style.removeProperty('--heading-y');el.style.removeProperty('--heading-opacity')});chapters.forEach(el=>el.querySelector('h2').style.removeProperty('translate'))}else schedule()});schedule()})();
